services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql-network

  seaside-hotel:
    build:
      context: .
      dockerfile: Dockerfile
    image: seaside-hotel:1.1.0
    container_name: seaside-hotel-container
    depends_on:
      - mysql
    ports:
      - "8080:9192"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - spring-mysql-network

networks:
  spring-mysql-network:
    driver: bridge

volumes:
  mysql-data: