apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deployment
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
        - name: {{ .Release.Name }}-mysql-container
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.databaseName }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-root-password
                  key: password

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: {{ .Release.Name }}-mysql-persistent-storage
              mountPath: {{ .Values.mysqlVolume.mountPath }}
      volumes:
        - name: {{ .Release.Name }}-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc